version: '2.0'

services:

# --------------------------------------------
 botmanager:
  build:
   context: ./botmanager
  env_file:
   - ./botmanager.env
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
  image: riopapa/coin_botmanager

# --------------------------------------------
 tracker_bch:
  build:
   context: ./tracker
  env_file:
   - tracker.env
   - ./config/bch/tracker.env
  environment:
   - CURRENCY=BCH
   - PRICE_ROUND_RADIX=-1
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/:/app/chartData/
  image: riopapa/coin_tracker

 tracker_btc:
  build:
   context: ./tracker
  env_file:
   - tracker.env
   - ./config/btc/tracker.env
  environment:
   - CURRENCY=BTC
   - PRICE_ROUND_RADIX=-3
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/:/app/chartData/
  image: riopapa/coin_tracker

 tracker_eth:
  build:
   context: ./tracker
  env_file:
   - tracker.env
   - ./config/eth/tracker.env
  environment:
   - CURRENCY=ETH
   - PRICE_ROUND_RADIX=-1
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/:/app/chartData/
  image: riopapa/coin_tracker

 tracker_btg:
  build:
   context: ./tracker
  env_file:
   - tracker.env
   - ./config/btc/tracker.env
  environment:
   - CURRENCY=BTG
   - PRICE_ROUND_RADIX=-2
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/:/app/chartData/
  image: riopapa/coin_tracker

